
GET http://localhost:8000/api/rues/?limit=1
Accept: */*
Cache-Control: no-cache
Authorization: Token c5c77bfae82fa61df18d2273e37c7bf421003cd0

###

GET http://localhost:8000/api/tarif/list/
Accept: */*
Cache-Control: no-cache
Authorization: Token c5c77bfae82fa61df18d2273e37c7bf421003cd0

###

GET http://localhost:8000/api/payes/?ordering=memo&pay_year=2018
Accept: */*
Cache-Control: no-cache
Authorization: Token c5c77bfae82fa61df18d2273e37c7bf421003cd0
