
GET http://localhost:8000/api/rues/?limit=1
Accept: */*
Cache-Control: no-cache
Authorization: Token 634bda8cfd3e13f3b96c09a840c06a49ff9b32c1

###

GET http://localhost:8000/api/tarif/list/
Accept: */*
Cache-Control: no-cache
Authorization: Token 634bda8cfd3e13f3b96c09a840c06a49ff9b32c1